[package]
name = "annelid"
version = "0.1.0"
edition = "2021"
description = "A speedrun timer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
#scan_fmt = "0.2.6"
websocket = "0"
livesplit-core = { version = "*", features = ["software-rendering", "font-loading"] }
epaint = "0.18"
eframe = "0.18"
egui = { version = "0.18", features = ["serde"] }
#egui_extras = "*"
lazy_static = "1"
strum = "0"
strum_macros = "0"
time = "0"
parking_lot = "*"
native-dialog = "0"
directories = "4"
roxmltree = "0"
clap = { version = "3", features = ["clap_derive", "derive"] }
toml = "0"
serde_derive = "1"
glow = "*"
bytemuck = { version = "*", features = ["derive"] }
egui_glow = "0.18"
memoffset = "*"


# Remember to test with --release
#[profile.dev]
#opt-level = 2
#debug = true

[package.metadata.bundle]
name = "Annelid"
identifier = "annelid"
copyright = "Copyright (c) Jason Dagit 2022. GPL 3."
short_description = "A speedrun timer."
long_description = """
A speedrun timer with autosplitter capabilities for USB2SNES.
"""
