[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-mmacosx-version-min=10.13",
    "-C", "link-arg=-Wl,-no_fixup_chains"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-mmacosx-version-min=10.13",
    "-C", "link-arg=-Wl,-no_fixup_chains"
]
